{
 "title": "Rosemary IDPS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"load15\" or r[\"_field\"] == \"load5\" or r[\"_field\"] == \"n_cpus\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System UpTime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\" or r[\"_field\"] == \"used\" or r[\"_field\"] == \"free\" or r[\"_field\"] == \"cached\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Blocked Events Log",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"event_type\"] != \"stats\")  \n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r[\"action\"] == \"blocked\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> map(fn: (r) => ({\n    time: r._time,\n    action: r.action,\n//    event_type: r.event_type,\n    signature: r.signature,\n    signature_id: string(v: r.signature_id),\n//    category: r.category,\n    protocol: r.proto,\n    src_ip: r.src_ip,\n    src_port: string(v: r.src_port),\n    dest_ip: r.dest_ip,\n    dest_port: string(v: r.dest_port)\n  }))\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> limit(n: 100, offset: 0)\n  |> yield(name: \"table\")"
    }
   ]
  },
  {
   "title": "Events Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"event_type\"] != \"stats\")  \n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> map(fn: (r) => ({\n    time: r._time,\n    action: r.action,\n//    event_type: r.event_type,\n    signature: r.signature,\n    signature_id: string(v: r.signature_id),\n//    category: r.category,\n    protocol: r.proto,\n    src_ip: r.src_ip,\n    src_port: string(v: r.src_port),\n    dest_ip: r.dest_ip,\n    dest_port: string(v: r.dest_port)\n  }))\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> limit(n: 50, offset: 0)\n  |> yield(name: \"table\")"
    }
   ]
  }
 ]
}