{
 "title": "Rosemary IDPS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_idle\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\" or r[\"_field\"] == \"used\" or r[\"_field\"] == \"free\" or r[\"_field\"] == \"cached\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\" or r[\"_field\"] == \"sleeping\" or r[\"_field\"] == \"running\" or r[\"_field\"] == \"total_threads\" or r[\"_field\"] == \"idle\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk I/O (mmcblk2p9)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_time\" or r[\"_field\"] == \"writes\" or r[\"_field\"] == \"write_bytes\" or r[\"_field\"] == \"reads\" or r[\"_field\"] == \"read_time\" or r[\"_field\"] == \"read_bytes\")\n  |> filter(fn: (r) => r[\"name\"] == \"mmcblk2p9\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk I/O (mmcblk0p9)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_time\" or r[\"_field\"] == \"writes\" or r[\"_field\"] == \"write_bytes\" or r[\"_field\"] == \"reads\" or r[\"_field\"] == \"read_time\" or r[\"_field\"] == \"read_bytes\")\n  |> filter(fn: (r) => r[\"name\"] == \"mmcblk0p9\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Blocked Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"event_type\"] != \"stats\")  \n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r[\"action\"] == \"blocked\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> map(fn: (r) => ({\n    time: r._time,\n    action: r.action,\n//    event_type: r.event_type,\n    signature: r.signature,\n    signature_id: string(v: r.signature_id),\n//    category: r.category,\n    protocol: r.proto,\n    src_ip: r.src_ip,\n    src_port: string(v: r.src_port),\n    dest_ip: r.dest_ip,\n    dest_port: string(v: r.dest_port)\n  }))\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> limit(n: 100, offset: 0)\n  |> yield(name: \"table\")"
    }
   ]
  },
  {
   "title": "All Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"suricata_events\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"event_type\"] != \"stats\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> map(fn: (r) => ({\n    time: r._time,\n    action: r.action,\n//    event_type: r.event_type,\n    signature: r.signature,\n    signature_id: string(v: r.signature_id),\n//    category: r.category,\n    protocol: r.proto,\n    src_ip: r.src_ip,\n    src_port: string(v: r.src_port),\n    dest_ip: r.dest_ip,\n    dest_port: string(v: r.dest_port)\n  }))\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> limit(n: 50, offset: 0) \n  |> yield(name: \"table\")\n\n\n"
    }
   ]
  }
 ]
}